
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.8.0"]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - uses: Randomblock1/theos-action@v1
      - name: Prepare Theos
      - name: Clone and Build Comet
         run:|
          git clone https://github.com/ginsudev/Comet.git
          cd Comet
          make clean all
        
      - name: Install Comet into Theos Library
        run: |
          mkdir -p $THEOS/lib/
          cp -r Comet/.theos/obj/* $THEOS/lib/
         #run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        # Don't use @main in production, this repo is specifically for testing it.
        uses: Randomblock1/theos-action@main
      - name: Build
        run: make
      

