
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.8.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Install_deps
        run:  |

           git clone https://github.com/theos/theos.git ~/theos

           cd ~/theos && git submodule update --init --recursive

           echo "export THEOS=~/theos" >> $GITHUB_ENV

           echo "export PATH=\$THEOS/bin:\$PATH" >> $GITHUB_ENV
           source $GITHUB_ENV
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
